/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import model.bean.Cliente;
import model.dao.ClienteDAO;

/**
 *
 * @author Ali2
 */
public class CadastroCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField16 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabeNome = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jOrgaoEmissor = new javax.swing.JTextField();
        jTextUfRg = new javax.swing.JTextField();
        jTextNaturalidade = new javax.swing.JTextField();
        jTextNomePai = new javax.swing.JTextField();
        jTextNomeMae = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jComboSexo = new javax.swing.JComboBox<>();
        jComboEstadoCivil = new javax.swing.JComboBox<>();
        jLabelCpf = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jLabelOrgaoEmissor = new javax.swing.JLabel();
        jLabelUfNome = new javax.swing.JLabel();
        jLabelDataEmissao = new javax.swing.JLabel();
        jLabelDataNascimento = new javax.swing.JLabel();
        jLabelNaturalidade = new javax.swing.JLabel();
        jLabelUfNaturalidade = new javax.swing.JLabel();
        jLabelNomePai = new javax.swing.JLabel();
        jLabelNomeMae = new javax.swing.JLabel();
        jLabelEstadoCivil = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextUfNaturalidade = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jFormattedCpf = new javax.swing.JFormattedTextField();
        jFormattedRg = new javax.swing.JFormattedTextField();
        jFormattedDataEmissao = new javax.swing.JFormattedTextField();
        jFormattedDataNascimento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jLabelTipoRes = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jTextEndereco = new javax.swing.JTextField();
        jTextBairro = new javax.swing.JTextField();
        jTextCidade = new javax.swing.JTextField();
        jComboTipoRes = new javax.swing.JComboBox<>();
        jFormattedCep = new javax.swing.JFormattedTextField();
        jFormattedTelefone = new javax.swing.JFormattedTextField();
        jFormattedCelular = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextEmpresa = new javax.swing.JTextField();
        jTextCargo = new javax.swing.JTextField();
        jTextBairroEmpresa = new javax.swing.JTextField();
        jTextEnderecoComercial = new javax.swing.JTextField();
        jTextOrigem = new javax.swing.JTextField();
        jTextCidadeEmpresa = new javax.swing.JTextField();
        jTextUfEmpresa = new javax.swing.JTextField();
        jTextRamal = new javax.swing.JTextField();
        jFormattedCnpj = new javax.swing.JFormattedTextField();
        jFormattedDataAdmissao = new javax.swing.JFormattedTextField();
        jFormattedTelefoneComprovacao = new javax.swing.JFormattedTextField();
        jComboPorteEmpresa = new javax.swing.JComboBox<>();
        jFormattedCepEmpresa = new javax.swing.JFormattedTextField();
        jFormattedTelefoneEmpresa = new javax.swing.JFormattedTextField();
        jFormattedRendaMensal = new javax.swing.JTextField();
        jFormattedRendaAdicional = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextBanco = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jFormattedAgencia = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextClienteDesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedConta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabelValorEmprestimo = new javax.swing.JLabel();
        jLabelPlano = new javax.swing.JLabel();
        jFormattedPlano = new javax.swing.JFormattedTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jFormattedValorEmprestimo = new javax.swing.JFormattedTextField();

        jTextField16.setText("jTextField16");

        jLabel15.setText("jLabel15");

        jLabel17.setText("jLabel17");

        jLabel27.setText("jLabel27");

        jTextField10.setText("jTextField10");

        jLabel48.setText("jLabel48");

        jTextField23.setText("jTextField23");

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeNome.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabeNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabeNome.setText("Nome Completo:");
        jPanel1.add(jLabeNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 196, -1));
        jPanel1.add(jOrgaoEmissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 74, -1));
        jPanel1.add(jTextUfRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 30, -1));
        jPanel1.add(jTextNaturalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 50, 100, -1));

        jTextNomePai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomePaiActionPerformed(evt);
            }
        });
        jPanel1.add(jTextNomePai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 196, -1));
        jPanel1.add(jTextNomeMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 196, -1));
        jPanel1.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 187, -1));

        jComboSexo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboSexo.setForeground(new java.awt.Color(255, 255, 255));
        jComboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Masculino", "Feminino" }));
        jPanel1.add(jComboSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 108, -1));

        jComboEstadoCivil.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        jComboEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Casado(a)", "Solteiro(a)", "Viúvo(a)" }));
        jPanel1.add(jComboEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 104, -1));

        jLabelCpf.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelCpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCpf.setText("CPF:");
        jPanel1.add(jLabelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabelRg.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelRg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRg.setText("RG:");
        jPanel1.add(jLabelRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabelOrgaoEmissor.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelOrgaoEmissor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrgaoEmissor.setText("Orgão Emissor:");
        jPanel1.add(jLabelOrgaoEmissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        jLabelUfNome.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelUfNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUfNome.setText("UF:");
        jPanel1.add(jLabelUfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 22, -1));

        jLabelDataEmissao.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelDataEmissao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataEmissao.setText("Data de emissão:");
        jPanel1.add(jLabelDataEmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, -1));

        jLabelDataNascimento.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataNascimento.setText("Data de Nascimento:");
        jPanel1.add(jLabelDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, -1, -1));

        jLabelNaturalidade.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelNaturalidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNaturalidade.setText("Naturalidade:");
        jPanel1.add(jLabelNaturalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        jLabelUfNaturalidade.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelUfNaturalidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUfNaturalidade.setText("UF:");
        jPanel1.add(jLabelUfNaturalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, -1, -1));

        jLabelNomePai.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelNomePai.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomePai.setText("Nome do pai:");
        jPanel1.add(jLabelNomePai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabelNomeMae.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelNomeMae.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeMae.setText("Nome da mãe:");
        jPanel1.add(jLabelNomeMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabelEstadoCivil.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstadoCivil.setText("Estado civil:");
        jPanel1.add(jLabelEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("E-mail:");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));
        jPanel1.add(jTextUfNaturalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 50, 44, -1));

        jLabelSexo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Sexo:");
        jPanel1.add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, -1, -1));

        jFormattedCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 160, -1));

        try {
            jFormattedRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 138, -1));

        jFormattedDataEmissao.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedDataEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedDataEmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 125, -1));

        jFormattedDataNascimento.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 128, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("End.Corresp:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Residencial", "Comercial", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1327, 159));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Residenciais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEndereco.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEndereco.setText("Endereço:");
        jPanel2.add(jLabelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 29, -1, -1));

        jLabelBairro.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairro.setText("Bairro:");
        jPanel2.add(jLabelBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 29, -1, -1));

        jLabelCidade.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelCidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCidade.setText("Cidade:");
        jPanel2.add(jLabelCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 29, -1, -1));

        jLabelCep.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelCep.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCep.setText("CEP:");
        jPanel2.add(jLabelCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 29, -1, -1));

        jLabelTipoRes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelTipoRes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoRes.setText("Tipo de Residência:");
        jPanel2.add(jLabelTipoRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 29, -1, -1));

        jLabelTelefone.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText("Telefone:");
        jPanel2.add(jLabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1064, 29, -1, -1));

        jLabelCelular.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCelular.setText("Celular:");
        jPanel2.add(jLabelCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 86, -1, -1));
        jPanel2.add(jTextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 53, 518, -1));
        jPanel2.add(jTextBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 53, 110, -1));
        jPanel2.add(jTextCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 53, 90, -1));

        jComboTipoRes.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboTipoRes.setForeground(new java.awt.Color(255, 255, 255));
        jComboTipoRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Própria", "Familiar", "Alugada" }));
        jPanel2.add(jComboTipoRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 50, 95, -1));

        jFormattedCep.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 53, 97, -1));

        jFormattedTelefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1064, 53, 101, -1));

        jFormattedCelular.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 107, 98, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 165, 1327, 148));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Profissionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Empresa/Orgão:");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("CNPJ:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 38, -1));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Data da Admissão:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Renda Mensal:");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Cargo/Função:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Renda Adicional:");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Origem:");
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Telefone de comprovação:");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Endereço Comercial:");
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Porte da empresa:");
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Bairro:");
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Cidade:");
        jPanel3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("CEP:");
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("UF:");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Telefone:");
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Ramal:");
        jPanel3.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));
        jPanel3.add(jTextEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, -1));
        jPanel3.add(jTextCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 105, -1));
        jPanel3.add(jTextBairroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 105, -1));
        jPanel3.add(jTextEnderecoComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 200, -1));

        jTextOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOrigemActionPerformed(evt);
            }
        });
        jPanel3.add(jTextOrigem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 90, -1));
        jPanel3.add(jTextCidadeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 81, -1));
        jPanel3.add(jTextUfEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 33, -1));
        jPanel3.add(jTextRamal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 88, -1));

        jFormattedCnpj.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jFormattedCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 118, -1));

        jFormattedDataAdmissao.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedDataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedDataAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedDataAdmissaoActionPerformed(evt);
            }
        });
        jPanel3.add(jFormattedDataAdmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 114, -1));

        jFormattedTelefoneComprovacao.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTelefoneComprovacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jFormattedTelefoneComprovacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 129, -1));

        jComboPorteEmpresa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboPorteEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        jComboPorteEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Pequena", "Média", "Grande" }));
        jPanel3.add(jComboPorteEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 88, -1));

        jFormattedCepEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedCepEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jFormattedCepEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, -1));

        jFormattedTelefoneEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTelefoneEmpresa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jFormattedTelefoneEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 116, -1));
        jPanel3.add(jFormattedRendaMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 110, -1));
        jPanel3.add(jFormattedRendaAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 319, 1327, 245));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Profissionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jTextBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 91, -1));

        jLabel46.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Banco:");
        jPanel4.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 29, -1, -1));

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Agência:");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 29, -1, -1));

        jFormattedAgencia.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedAgencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel4.add(jFormattedAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 50, 80, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N°Conta");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 29, -1, -1));
        jPanel4.add(jTextClienteDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 50, 80, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliende desde:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 29, -1, -1));
        jPanel4.add(jFormattedConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 100, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1327, 91));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Profissionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelValorEmprestimo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelValorEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValorEmprestimo.setText("Valor do empréstimo:");
        jPanel5.add(jLabelValorEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 29, -1, -1));

        jLabelPlano.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabelPlano.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlano.setText("Plano:");
        jPanel5.add(jLabelPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 29, -1, -1));

        jFormattedPlano.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedPlano.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###x")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel5.add(jFormattedPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 50, 71, -1));

        jButtonCadastrar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 50, -1, -1));

        jFormattedValorEmprestimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jPanel5.add(jFormattedValorEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 50, 112, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 667, 1327, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomePaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomePaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomePaiActionPerformed

    private void jFormattedDataAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedDataAdmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedDataAdmissaoActionPerformed

    private void jTextOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOrigemActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       
        Cliente c = new Cliente();
        ClienteDAO dao = new ClienteDAO();
        
        c.setNome(jNome.getText());
        c.setCpf(jFormattedCpf.getText());
        c.setRg(jFormattedRg.getText());
        c.setOrgao_emissor(jOrgaoEmissor.getText());
        c.setUf(jTextUfRg.getText());
        c.setData_emissao(jFormattedDataNascimento.getText());
        c.setData_nascimento(jFormattedDataNascimento.getText());
        c.setNaturalidade(jTextNaturalidade.getText());
        c.setSexo((String) jComboSexo.getSelectedItem());
        c.setNome_pai(jTextNomePai.getText());
        c.setNome_mae(jTextNomeMae.getText());
        c.setEstado_civil((String) jComboEstadoCivil.getSelectedItem());
        c.setEmail(jTextEmail.getText());
        c.setEnd_corresp(jTextEmail.getText());
        c.setEndereco(jTextEndereco.getText());
        c.setBairro(jTextBairro.getText());
        c.setCidade(jTextCidade.getText());
        c.setCep(jFormattedCep.getText());
        c.setTelefone(jFormattedTelefone.getText());
        c.setCelular(jFormattedCelular.getText());
        c.setEmpresa(jTextEmpresa.getText());
        c.setCnpj(jFormattedCnpj.getText());
        c.setData_admissao(jFormattedDataAdmissao.getText());
        c.setRenda_mensal((jFormattedRendaMensal.getText()));
        c.setCargo(jTextCargo.getText());
        c.setRenda_adicional((jFormattedRendaAdicional.getText()));
        c.setOrigem(jTextOrigem.getText());
        c.setTelefone_de_comprovacao(jFormattedTelefoneComprovacao.getText());
        c.setEndereco_comercial(jTextEnderecoComercial.getText());
        c.setPorte_da_empresa((String)jComboPorteEmpresa.getSelectedItem());
        c.setBairro_empresa(jTextBairroEmpresa.getText());
        c.setCidade_empresa(jTextCidadeEmpresa.getText());
        c.setCep_empresa(jFormattedCepEmpresa.getText());
        c.setUf_empresa(jTextUfEmpresa.getText());
        c.setTelefone_empresa(jFormattedTelefoneEmpresa.getText());
        c.setRamal(jTextRamal.getText());
        c.setBanco(jTextBanco.getText());
        c.setAgencia(jFormattedAgencia.getText());
        c.setN_conta(jFormattedConta.getText());
        c.setCliente_desde(jTextClienteDesde.getText());
        c.setValor_do_emprestimo((jFormattedValorEmprestimo.getText()));
        c.setPlano(jFormattedPlano.getText());
        dao.create(c);
        
        jNome.setText("");
        jFormattedCpf.setText("");
        jFormattedRg.setText("");
        jOrgaoEmissor.setText("");
        jTextUfRg.setText("");
        jFormattedDataEmissao.setText("");
        jFormattedDataNascimento.setText("");
        jTextNaturalidade.setText("");
        jTextNomePai.setText("");
        jTextNomeMae.setText("");
        jTextEmail.setText("");
        jTextEndereco.setText("");
        jTextBairro.setText("");
        jTextCidade.setText("");
        jFormattedCep.setText("");
        jFormattedTelefone.setText("");
        jFormattedCelular.setText("");
        jTextEmpresa.setText("");
        jFormattedCnpj.setText("");
        jFormattedDataAdmissao.setText("");
        jFormattedRendaMensal.setText("");
        jTextOrigem.setText("");
        jFormattedTelefoneComprovacao.setText("");
        jTextEnderecoComercial.setText("");
        jTextBairroEmpresa.setText("");
        jTextCidadeEmpresa.setText("");
        jFormattedCepEmpresa.setText("");
        jTextUfEmpresa.setText("");
        jFormattedTelefoneEmpresa.setText("");
        jTextRamal.setText("");
        jTextBanco.setText("");
        jFormattedAgencia.setText("");
        jFormattedConta.setText("");
        jTextClienteDesde.setText("");
        jFormattedPlano.setText("");
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboEstadoCivil;
    private javax.swing.JComboBox<String> jComboPorteEmpresa;
    private javax.swing.JComboBox<String> jComboSexo;
    private javax.swing.JComboBox<String> jComboTipoRes;
    private javax.swing.JFormattedTextField jFormattedAgencia;
    private javax.swing.JFormattedTextField jFormattedCelular;
    private javax.swing.JFormattedTextField jFormattedCep;
    private javax.swing.JFormattedTextField jFormattedCepEmpresa;
    private javax.swing.JFormattedTextField jFormattedCnpj;
    private javax.swing.JTextField jFormattedConta;
    private javax.swing.JFormattedTextField jFormattedCpf;
    private javax.swing.JFormattedTextField jFormattedDataAdmissao;
    private javax.swing.JFormattedTextField jFormattedDataEmissao;
    private javax.swing.JFormattedTextField jFormattedDataNascimento;
    private javax.swing.JFormattedTextField jFormattedPlano;
    private javax.swing.JTextField jFormattedRendaAdicional;
    private javax.swing.JTextField jFormattedRendaMensal;
    private javax.swing.JFormattedTextField jFormattedRg;
    private javax.swing.JFormattedTextField jFormattedTelefone;
    private javax.swing.JFormattedTextField jFormattedTelefoneComprovacao;
    private javax.swing.JFormattedTextField jFormattedTelefoneEmpresa;
    private javax.swing.JFormattedTextField jFormattedValorEmprestimo;
    private javax.swing.JLabel jLabeNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataEmissao;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstadoCivil;
    private javax.swing.JLabel jLabelNaturalidade;
    private javax.swing.JLabel jLabelNomeMae;
    private javax.swing.JLabel jLabelNomePai;
    private javax.swing.JLabel jLabelOrgaoEmissor;
    private javax.swing.JLabel jLabelPlano;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTipoRes;
    private javax.swing.JLabel jLabelUfNaturalidade;
    private javax.swing.JLabel jLabelUfNome;
    private javax.swing.JLabel jLabelValorEmprestimo;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jOrgaoEmissor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextBairroEmpresa;
    private javax.swing.JTextField jTextBanco;
    private javax.swing.JTextField jTextCargo;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextCidadeEmpresa;
    private javax.swing.JTextField jTextClienteDesde;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmpresa;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextEnderecoComercial;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextNaturalidade;
    private javax.swing.JTextField jTextNomeMae;
    private javax.swing.JTextField jTextNomePai;
    private javax.swing.JTextField jTextOrigem;
    private javax.swing.JTextField jTextRamal;
    private javax.swing.JTextField jTextUfEmpresa;
    private javax.swing.JTextField jTextUfNaturalidade;
    private javax.swing.JTextField jTextUfRg;
    // End of variables declaration//GEN-END:variables
}
