/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable.PrintMode;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Cliente;
import model.dao.ClienteDAO;

/**
 *
 * @author User
 */
public class PesquisaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form PesquisaCliente
     */
    public PesquisaCliente() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTCliente.getModel();
        jTCliente.setRowSorter(new TableRowSorter(modelo));
        
        readJtable();
    }
    
    public void readJtable(){
        DefaultTableModel modelo = (DefaultTableModel) jTCliente.getModel();
        modelo.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();
        
        for(Cliente c: cdao.read()){
        
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf(),
                c.getRg(),
                c.getOrgao_emissor(),
                c.getUf(),
                c.getData_emissao(),
                c.getData_nascimento(),
                c.getNaturalidade(),
                c.getSexo(),
                c.getNome_pai(),
                c.getNome_mae(),
                c.getEstado_civil(),
                c.getEnd_corresp(),
                c.getEmail(),
                c.getEndereco(),
                c.getBairro(),
                c.getCidade(),
                c.getCep(),
                c.getTelefone(),
                c.getCelular(),
                c.getEmpresa(),
                c.getCnpj(),
                c.getData_admissao(),
                c.getRenda_mensal(),
                c.getCargo(),
                c.getRenda_adicional(),
                c.getOrigem(),
                c.getTelefone_de_comprovacao(),
                c.getEndereco_comercial(),
                c.getPorte_da_empresa(),
                c.getBairro_empresa(),
                c.getCidade_empresa(),
                c.getCep_empresa(),
                c.getUf_empresa(),
                c.getTelefone_empresa(),
                c.getRamal(),
                c.getBanco(),
                c.getAgencia(),
                c.getN_conta(),
                c.getCliente_desde(),
                c.getValor_do_emprestimo(),
                c.getPlano()
            });
            
        }
        
    }
    public void readJtableForCpf(String cpf){
        DefaultTableModel modelo = (DefaultTableModel) jTCliente.getModel();
        modelo.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();
        
        for(Cliente c: cdao.readForCpf(cpf)){
        
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCpf(),
                c.getRg(),
                c.getOrgao_emissor(),
                c.getUf(),
                c.getData_emissao(),
                c.getData_nascimento(),
                c.getNaturalidade(),
                c.getSexo(),
                c.getNome_pai(),
                c.getNome_mae(),
                c.getEstado_civil(),
                c.getEnd_corresp(),
                c.getEmail(),
                c.getEndereco(),
                c.getBairro(),
                c.getCidade(),
                c.getCep(),
                c.getTelefone(),
                c.getCelular(),
                c.getEmpresa(),
                c.getCnpj(),
                c.getData_admissao(),
                c.getRenda_mensal(),
                c.getCargo(),
                c.getRenda_adicional(),
                c.getOrigem(),
                c.getTelefone_de_comprovacao(),
                c.getEndereco_comercial(),
                c.getPorte_da_empresa(),
                c.getBairro_empresa(),
                c.getCidade_empresa(),
                c.getCep_empresa(),
                c.getUf_empresa(),
                c.getTelefone_empresa(),
                c.getRamal(),
                c.getBanco(),
                c.getAgencia(),
                c.getN_conta(),
                c.getCliente_desde(),
                c.getValor_do_emprestimo(),
                c.getPlano()                    
            });
            
        }
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCliente = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOrgaoEmissor = new javax.swing.JTextField();
        txtUf = new javax.swing.JTextField();
        txtDataEmissao = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        txtNaturalidade = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtNomePai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNomeMae = new javax.swing.JTextField();
        txtEstadoCivil = new javax.swing.JTextField();
        txtEndCorresp = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        txtDataAdmissao = new javax.swing.JTextField();
        txtRendaMensal = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtRendaAdicional = new javax.swing.JTextField();
        txtOrigem = new javax.swing.JTextField();
        txtTelefoneComprovacao = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtEnderecoComercial = new javax.swing.JTextField();
        txtCepEmpresa = new javax.swing.JTextField();
        txtTelefoneEmpresa = new javax.swing.JTextField();
        txtUfEmpresa = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtRamal = new javax.swing.JTextField();
        txtBanco = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        txtConta = new javax.swing.JTextField();
        txtValorEmprestimo = new javax.swing.JTextField();
        txtPlano = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtPorteEmpresa = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtBairroEmpresa = new javax.swing.JTextField();
        txtCidadeEmpresa = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtClienteDesde = new javax.swing.JTextField();
        ButtonRelatorio = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setClosable(true);
        setMaximizable(true);
        setFrameIcon(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 140, -1));

        jButtonPesquisar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 90, 20));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CPF:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 163, 30));

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        jPanel2.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 160, 30));

        txtRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGActionPerformed(evt);
            }
        });
        jPanel2.add(txtRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, 126, 30));

        jTCliente.setBackground(new java.awt.Color(153, 153, 153));
        jTCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTCliente.setForeground(new java.awt.Color(255, 255, 255));
        jTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "OrgaoEmissor", "Uf", "DataEmissao", "DataNascimento", "Naturalidade", "Sexo", "NomePai", "NomeMae", "EstadoCivil", "EndCorresp", "Email", "Endereco", "Bairro", "Cidade", "CEP", "Telefone", "Celular", "Empresa", "CNPJ", "DataAdmissao", "RendeMensal", "Cargo", "RendaAdicional", "Origem", "TelefoneComprovacao", "EnderecoComercial", "PorteEmpresa", "BairroEmpresa", "CidadeEmpresa", "CepEmpresa", "UfEmpresa", "TelefoneEmpresa", "Ramal", "Banco", "Agencia", "Conta", "ClienteDesde", "ValorEmprestimo", "Plano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClienteMouseClicked(evt);
            }
        });
        jTCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTCliente);
        if (jTCliente.getColumnModel().getColumnCount() > 0) {
            jTCliente.getColumnModel().getColumn(0).setMinWidth(20);
            jTCliente.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTCliente.getColumnModel().getColumn(3).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(4).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(5).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(6).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(7).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(8).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(8).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(9).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(9).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(10).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(11).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(11).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(12).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(12).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(13).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(13).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(14).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(14).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(15).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(15).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(16).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(16).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(17).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(17).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(18).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(18).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(19).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(19).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(20).setMinWidth(100);
            jTCliente.getColumnModel().getColumn(20).setPreferredWidth(100);
            jTCliente.getColumnModel().getColumn(21).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(21).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(22).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(22).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(23).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(23).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(24).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(24).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(25).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(25).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(26).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(26).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(27).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(27).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(28).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(28).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(29).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(29).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(30).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(30).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(31).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(31).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(32).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(32).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(33).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(33).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(34).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(34).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(35).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(35).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(36).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(36).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(37).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(37).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(38).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(38).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(39).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(39).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(40).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(40).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(41).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(41).setPreferredWidth(0);
            jTCliente.getColumnModel().getColumn(42).setMinWidth(0);
            jTCliente.getColumnModel().getColumn(42).setPreferredWidth(0);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 690));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Atualizar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, 20));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RG:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, -1));
        jPanel2.add(txtOrgaoEmissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 90, 80, 30));
        jPanel2.add(txtUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 90, 40, 30));
        jPanel2.add(txtDataEmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 90, 80, 30));
        jPanel2.add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 90, 90, 30));
        jPanel2.add(txtNaturalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 90, 70, 30));
        jPanel2.add(txtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 90, 80, 30));
        jPanel2.add(txtNomePai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 90, 120, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Orgão emissor:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UF:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data de emissão:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Data de Nascimento:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Naturalidade:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sexo:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nome do Pai:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 70, -1, -1));
        jPanel2.add(txtNomeMae, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 140, 30));
        jPanel2.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 169, 90, 30));
        jPanel2.add(txtEndCorresp, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 100, 30));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 169, 180, 30));
        jPanel2.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 169, 240, 30));
        jPanel2.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 169, 80, 30));
        jPanel2.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 169, 80, 30));
        jPanel2.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 169, 110, 30));
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 169, 120, 30));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nome da Mãe:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Estado Civil:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("End.Correspondente:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Endereço:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Bairro:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 150, -1, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cidade:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 150, -1, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CEP:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 150, -1, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Telefone:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1770, 150, -1, -1));
        jPanel2.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 110, 30));
        jPanel2.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 110, 30));
        jPanel2.add(txtDataAdmissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 100, 30));
        jPanel2.add(txtRendaMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 100, 30));
        jPanel2.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 250, 80, 30));
        jPanel2.add(txtRendaAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 250, 90, 30));
        jPanel2.add(txtOrigem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 250, 80, 30));
        jPanel2.add(txtTelefoneComprovacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 250, 130, 30));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Celular:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, -1));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CNPJ:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Data de Admissão:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, -1, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Renda Mensal:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, -1, -1));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Cargo:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Renda Adicional:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 230, -1, -1));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Origem:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 230, -1, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Telefone de Comprovação:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 230, -1, -1));
        jPanel2.add(txtEnderecoComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 250, 210, 30));
        jPanel2.add(txtCepEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 100, 30));
        jPanel2.add(txtTelefoneEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 110, 30));
        jPanel2.add(txtUfEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 40, 30));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Endereço Comercial:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 230, -1, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("CEP:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 310, -1, -1));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("UF:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, -1, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Telefone da Empresa:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 310, -1, -1));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Ramal:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 310, -1, -1));
        jPanel2.add(txtRamal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 330, 70, 30));
        jPanel2.add(txtBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 70, 30));
        jPanel2.add(txtAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 439, 70, 30));
        jPanel2.add(txtConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 439, 100, 30));
        jPanel2.add(txtValorEmprestimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 110, 30));
        jPanel2.add(txtPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 70, 30));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Banco:");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Agência:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("N° Conta:");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, -1, -1));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Valor do Emprestimo:");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, -1, -1));

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Plano:");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 420, -1, -1));
        jPanel2.add(txtPorteEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 100, 30));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Porte da Empresa:");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));
        jPanel2.add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 150, 30));

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Empresa:");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Bairro da Empresa:");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));
        jPanel2.add(txtBairroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 100, 30));
        jPanel2.add(txtCidadeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 110, 30));

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Cidade da Empresa:");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Cliente desde:");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));
        jPanel2.add(txtClienteDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 439, 100, 30));

        ButtonRelatorio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ButtonRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        ButtonRelatorio.setText("Emitir Relatório");
        ButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRelatorioActionPerformed(evt);
            }
        });
        jPanel2.add(ButtonRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 650, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        
        readJtableForCpf(jPesquisar.getText());

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void txtRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked



    }//GEN-LAST:event_jButton2MouseClicked

    private void jTClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClienteMouseClicked

        if(jTCliente.getSelectedRow() != -1){
            txtNome.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 1).toString());
            txtCPF.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 2).toString());
            txtRG.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 3).toString());
            txtOrgaoEmissor.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 4).toString());
            txtUf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 5).toString());
            txtDataEmissao.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 6).toString());
            txtDataNascimento.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 7).toString());
            txtNaturalidade.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 8).toString());
            txtSexo.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 9).toString());
            txtNomePai.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 10).toString());
            txtNomeMae.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 11).toString());
            txtEstadoCivil.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 12).toString());
            txtEndCorresp.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 13).toString());
            txtEmail.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 14).toString());
            txtEndereco.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 15).toString());
            txtBairro.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 16).toString());
            txtCidade.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 17).toString());
            txtCep.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 18).toString());
            txtTelefone.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 19).toString());
            txtCelular.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 20).toString());
            txtEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 21).toString());
            txtCnpj.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 22).toString());
            txtDataAdmissao.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 23).toString());
            txtRendaMensal.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 24).toString());
            txtCargo.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 25).toString());
            txtRendaAdicional.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 26).toString());
            txtOrigem.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 27).toString());
            txtTelefoneComprovacao.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 28).toString());
            txtEnderecoComercial.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 29).toString());
            txtPorteEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 30).toString());
            txtBairroEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 31).toString());
            txtCidadeEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 32).toString());
            txtCepEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 33).toString());
            txtUfEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 34).toString());
            txtTelefoneEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 35).toString());
            txtRamal.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 36).toString());
            txtBanco.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 37).toString());
            txtAgencia.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 38).toString());
            txtConta.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 39).toString());
            txtClienteDesde.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 40).toString());
            txtValorEmprestimo.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 41).toString());
            txtPlano.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 42).toString());   
        }
        
    }//GEN-LAST:event_jTClienteMouseClicked

    private void jTClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClienteKeyReleased

        if(jTCliente.getSelectedRow()!= -1){
            
            txtNome.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 1).toString());
            txtCPF.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 2).toString());
            txtRG.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 3).toString());
            txtOrgaoEmissor.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 4).toString());
            txtUf.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 5).toString());
            txtDataEmissao.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 6).toString());
            txtDataNascimento.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 7).toString());
            txtNaturalidade.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 8).toString());
            txtSexo.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 9).toString());
            txtNomePai.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 10).toString());
            txtNomeMae.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 11).toString());
            txtEstadoCivil.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 12).toString());
            txtEndCorresp.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 13).toString());
            txtEmail.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 14).toString());
            txtEndereco.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 15).toString());
            txtBairro.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 16).toString());
            txtCidade.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 17).toString());
            txtCep.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 18).toString());
            txtTelefone.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 19).toString());
            txtCelular.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 20).toString());
            txtEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 21).toString());
            txtCnpj.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 22).toString());
            txtDataAdmissao.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 23).toString());
            txtRendaMensal.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 24).toString());
            txtCargo.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 25).toString());
            txtRendaAdicional.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 26).toString());
            txtOrigem.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 27).toString());
            txtTelefoneComprovacao.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 28).toString());
            txtEnderecoComercial.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 29).toString());
            txtPorteEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 30).toString());
            txtBairroEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 31).toString());
            txtCidadeEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 32).toString());
            txtCepEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 33).toString());
            txtUfEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 34).toString());
            txtTelefoneEmpresa.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 35).toString());
            txtRamal.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 36).toString());
            txtBanco.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 37).toString());
            txtAgencia.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 38).toString());
            txtConta.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 39).toString());
            txtClienteDesde.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 40).toString());
            txtValorEmprestimo.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 41).toString());
            txtPlano.setText(jTCliente.getValueAt(jTCliente.getSelectedRow(), 42).toString());          
        }

    }//GEN-LAST:event_jTClienteKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        if(jTCliente.getSelectedRow()!= -1){
            
            Cliente c = new Cliente();
            ClienteDAO dao = new ClienteDAO();

            c.setNome(txtNome.getText());
            c.setCpf(txtCPF.getText());
            c.setRg(txtRG.getText());
            c.setOrgao_emissor(txtOrgaoEmissor.getText());
            c.setUf(txtUf.getText());
            c.setData_emissao(txtDataEmissao.getText());
            c.setData_nascimento(txtDataNascimento.getText());
            c.setNaturalidade(txtNaturalidade.getText());
            c.setSexo((String) txtSexo.getText());
            c.setNome_pai(txtNomePai.getText());
            c.setNome_mae(txtNomeMae.getText());
            c.setEstado_civil((String) txtEstadoCivil.getText());
            c.setEnd_corresp((String) txtEndCorresp.getText());
            c.setEmail(txtEmail.getText());
            c.setEndereco(txtEndereco.getText());
            c.setBairro(txtBairro.getText());
            c.setCidade(txtCidade.getText());
            c.setCep(txtCep.getText());
            c.setTelefone(txtTelefone.getText());
            c.setCelular(txtCelular.getText());
            c.setEmpresa(txtEmpresa.getText());
            c.setCnpj(txtCnpj.getText());
            c.setData_admissao(txtDataAdmissao.getText());
            c.setRenda_mensal((txtRendaMensal.getText()));
            c.setCargo(txtCargo.getText());
            c.setRenda_adicional((txtRendaAdicional.getText()));
            c.setOrigem(txtOrigem.getText());
            c.setTelefone_de_comprovacao(txtTelefoneComprovacao.getText());
            c.setEndereco_comercial(txtEnderecoComercial.getText());
            c.setPorte_da_empresa((String)txtPorteEmpresa.getText());
            c.setBairro_empresa(txtBairroEmpresa.getText());
            c.setCidade_empresa(txtCidadeEmpresa.getText());
            c.setCep_empresa(txtCepEmpresa.getText());
            c.setUf_empresa(txtUfEmpresa.getText());
            c.setTelefone_empresa(txtTelefoneEmpresa.getText());
            c.setRamal(txtRamal.getText());
            c.setBanco(txtBanco.getText());
            c.setAgencia(txtAgencia.getText());
            c.setN_conta(txtConta.getText());
            c.setCliente_desde(txtClienteDesde.getText());
            c.setValor_do_emprestimo((txtValorEmprestimo.getText()));
            c.setPlano(txtPlano.getText());
            c.setId((int) jTCliente.getValueAt(jTCliente.getSelectedRow(), 0));
            dao.update(c);
            
            txtNome.setText("");
            txtCPF.setText("");
            txtRG.setText("");
            txtOrgaoEmissor.setText("");
            txtUf.setText("");
            txtDataEmissao.setText("");
            txtDataNascimento.setText("");
            txtNaturalidade.setText("");
            txtSexo.setText("");
            txtNomePai.setText("");
            txtNomeMae.setText("");
            txtEstadoCivil.setText("");
            txtEndCorresp.setText("");
            txtEmail.setText("");
            txtEndereco.setText("");
            txtBairro.setText("");
            txtCidade.setText("");
            txtCep.setText("");
            txtTelefone.setText("");
            txtCelular.setText("");
            txtEmpresa.setText("");
            txtCnpj.setText("");
            txtDataAdmissao.setText("");
            txtRendaMensal.setText("");
            txtOrigem.setText("");
            txtTelefoneComprovacao.setText("");
            txtEnderecoComercial.setText("");
            txtBairroEmpresa.setText("");
            txtCidadeEmpresa.setText("");
            txtCepEmpresa.setText("");
            txtUfEmpresa.setText("");
            txtTelefoneEmpresa.setText("");
            txtRamal.setText("");
            txtBanco.setText("");
            txtAgencia.setText("");
            txtConta.setText("");
            txtClienteDesde.setText("");
            txtPlano.setText("");
            
            readJtable();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRelatorioActionPerformed

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(jTCliente.getPrintable(PrintMode.FIT_WIDTH, null, null));
        job.setJobName("Nome do Trabalho de impressão");
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(PesquisaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ButtonRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRelatorio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCliente;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtBairroEmpresa;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCepEmpresa;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCidadeEmpresa;
    private javax.swing.JTextField txtClienteDesde;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtDataAdmissao;
    private javax.swing.JTextField txtDataEmissao;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEndCorresp;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEnderecoComercial;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeMae;
    private javax.swing.JTextField txtNomePai;
    private javax.swing.JTextField txtOrgaoEmissor;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JTextField txtPlano;
    private javax.swing.JTextField txtPorteEmpresa;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtRamal;
    private javax.swing.JTextField txtRendaAdicional;
    private javax.swing.JTextField txtRendaMensal;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefoneComprovacao;
    private javax.swing.JTextField txtTelefoneEmpresa;
    private javax.swing.JTextField txtUf;
    private javax.swing.JTextField txtUfEmpresa;
    private javax.swing.JTextField txtValorEmprestimo;
    // End of variables declaration//GEN-END:variables
}
