/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.ParceiroFisico;
import model.dao.ParceiroFisicoDAO;

/**
 *
 * @author User
 */
public class PesquisarParceiroFisico extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroParceiroFisico
     */
    public PesquisarParceiroFisico() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTParceiroFisico.getModel();
        jTParceiroFisico.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTParceiroFisico.getModel();
        modelo.setNumRows(0);
        ParceiroFisicoDAO pdao = new ParceiroFisicoDAO();
        
        for(ParceiroFisico p: pdao.read()){
        
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCpf(),
                p.getRg(),
                p.getOrgao_emissor(),
                p.getUf(),
                p.getCelular(),
                p.getEmail(),
                p.getEndereco(),
                p.getCep(),
                p.getCidade(),
                p.getEstado(),
                p.getTelefone(),
                p.getSite(),
                p.getBanco(),
                p.getAg(),
                p.getCc(),
                p.getNome_banco(),
                p.getCpf_banco(),
                p.getPix()
            });
            
        }
        
    }
    public void readJTableForCpf(String cpf){
        DefaultTableModel modelo = (DefaultTableModel) jTParceiroFisico.getModel();
        modelo.setNumRows(0);
        ParceiroFisicoDAO pdao = new ParceiroFisicoDAO();
        
        for(ParceiroFisico p: pdao.readForCpf(cpf)){
        
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getCpf(),
                p.getRg(),
                p.getOrgao_emissor(),
                p.getUf(),
                p.getCelular(),
                p.getEmail(),
                p.getEndereco(),
                p.getCep(),
                p.getCidade(),
                p.getEstado(),
                p.getTelefone(),
                p.getSite(),
                p.getBanco(),
                p.getAg(),
                p.getCc(),
                p.getNome_banco(),
                p.getCpf_banco(),
                p.getPix()
            });
            
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPesquisar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        txtNomeFantasia = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTParceiro = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jPesquisar1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRazao1 = new javax.swing.JTextField();
        txtNomeFantasia1 = new javax.swing.JTextField();
        txtEndereco1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTParceiro1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButtonAtualizar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPesquisar3 = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTParceiroFisico = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizar2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtOrgaoEmissor = new javax.swing.JTextField();
        txtUf = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        TxtEndereco = new javax.swing.JTextField();
        txtCep = new javax.swing.JTextField();
        txtAgencia = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtSite = new javax.swing.JTextField();
        txtBanco = new javax.swing.JTextField();
        txtConta = new javax.swing.JTextField();
        txtNomeBanco = new javax.swing.JTextField();
        txtCpfBanco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPix = new javax.swing.JTextField();
        jButtonRelatorio = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 140, -1));

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 90, 20));

        jLabel1.setText("CPF:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));
        jPanel2.add(txtRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 163, 30));

        txtNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFantasiaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 160, 30));

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        jPanel2.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 260, 30));

        jTParceiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Razao social", "Nome fantasia", "Endereço"
            }
        ));
        jTParceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTParceiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTParceiro);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 680));

        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, -1, 20));

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, 20));

        jLabel2.setText("Razão Social");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel3.setText("Nome fantasia:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        jLabel4.setText("Endereço:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 340, 0, 0));

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setMaximizable(true);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPesquisar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 140, -1));

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 90, 20));

        jLabel5.setText("CPF:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));
        jPanel3.add(txtRazao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 163, 30));

        txtNomeFantasia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeFantasia1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtNomeFantasia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 160, 30));

        txtEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEndereco1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtEndereco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 260, 30));

        jTParceiro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Razao social", "Nome fantasia", "Endereço"
            }
        ));
        jTParceiro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTParceiro1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTParceiro1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 680));

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, -1, 20));

        jButtonAtualizar1.setText("Atualizar");
        jButtonAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAtualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, 20));

        jLabel6.setText("Razão Social");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel7.setText("Nome fantasia:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        jLabel8.setText("Endereço:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jInternalFrame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 340, 0, 0));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPesquisar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 140, -1));

        jButtonPesquisar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 90, 20));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CPF:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));
        jPanel4.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 210, 30));

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        jPanel4.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 140, 30));

        txtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRgActionPerformed(evt);
            }
        });
        jPanel4.add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 130, 30));

        jTParceiroFisico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTParceiroFisico.setForeground(new java.awt.Color(255, 255, 255));
        jTParceiroFisico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "OrgaoEmissor", "Uf", "Celular", "Email", "Endereco", "Cep", "Cidade", "Estado", "Telefone", "Site", "Banco", "Agencia", "Conta", "NomeBanco", "CpfBanco", "Chave Pix"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTParceiroFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTParceiroFisicoMouseClicked(evt);
            }
        });
        jTParceiroFisico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTParceiroFisicoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTParceiroFisico);
        if (jTParceiroFisico.getColumnModel().getColumnCount() > 0) {
            jTParceiroFisico.getColumnModel().getColumn(0).setMinWidth(20);
            jTParceiroFisico.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTParceiroFisico.getColumnModel().getColumn(3).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(3).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(4).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(5).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(6).setMinWidth(100);
            jTParceiroFisico.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTParceiroFisico.getColumnModel().getColumn(7).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(8).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(8).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(9).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(9).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(10).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(11).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(11).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(12).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(12).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(13).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(13).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(14).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(14).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(15).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(15).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(16).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(16).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(17).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(17).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(18).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(18).setPreferredWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(19).setMinWidth(0);
            jTParceiroFisico.getColumnModel().getColumn(19).setPreferredWidth(0);
        }

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 680));

        jButtonExcluir.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, 20));

        jButtonAtualizar2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonAtualizar2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtualizar2.setText("Atualizar");
        jButtonAtualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizar2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAtualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, 20));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cpf:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rg:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));
        jPanel4.add(txtOrgaoEmissor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 79, 80, 30));
        jPanel4.add(txtUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 79, 40, 30));
        jPanel4.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 79, 90, 30));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel4.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 79, 170, 30));
        jPanel4.add(TxtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 79, 230, 30));
        jPanel4.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 189, 120, 30));
        jPanel4.add(txtAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 319, 80, 30));
        jPanel4.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 189, 90, 30));
        jPanel4.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 189, 100, 30));
        jPanel4.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 189, 120, 30));
        jPanel4.add(txtSite, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 189, 190, 30));
        jPanel4.add(txtBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 100, 30));
        jPanel4.add(txtConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 319, 70, 30));
        jPanel4.add(txtNomeBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 319, 190, 30));
        jPanel4.add(txtCpfBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 319, 150, 30));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Orgão Emissor:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("UF:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 60, -1, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Celular:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 60, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Email:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Endereço:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CEP:");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cidade:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Estado:");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Telefone:");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Site:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Banco:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Agência:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Conta:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, -1, -1));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nome:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, -1, -1));

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CPF:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 300, -1, -1));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Chave PIX:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 300, -1, -1));
        jPanel4.add(txtPix, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 320, 200, 30));

        jButtonRelatorio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButtonRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRelatorio.setText("Emitir Relatório");
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFantasiaActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void jTParceiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTParceiroMouseClicked

        if(jTParceiroFisico.getSelectedRow() != -1){
            txtNome.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 1).toString());
            txtCpf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 2).toString());
            txtRg.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 3).toString());
            txtOrgaoEmissor.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 4).toString());
            txtUf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 5).toString());
            txtCelular.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 6).toString());
            txtEmail.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 7).toString());
            TxtEndereco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 8).toString());
            txtCep.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 9).toString());
            txtCidade.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 10).toString());
            txtEstado.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 11).toString());
            txtTelefone.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 12).toString());
            txtSite.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 13).toString());
            txtBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 14).toString());
            txtAgencia.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 15).toString());
            txtConta.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 16).toString());
            txtNomeBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 17).toString());
            txtCpfBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 18).toString());
            txtPix.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 19).toString());
        }
    }//GEN-LAST:event_jTParceiroMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if(jTParceiroFisico.getSelectedRow() != -1){
            DefaultTableModel modelo = (DefaultTableModel) jTParceiroFisico.getModel();
            modelo.removeRow(jTParceiroFisico.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um parceiro para excluir");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtNomeFantasia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeFantasia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeFantasia1ActionPerformed

    private void txtEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndereco1ActionPerformed

    private void jTParceiro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTParceiro1MouseClicked

        if(jTParceiroFisico.getSelectedRow() != -1){
            
            txtNome.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 1).toString());
            txtCpf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 2).toString());
            txtRg.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 3).toString());
            txtOrgaoEmissor.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 4).toString());
            txtUf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 5).toString());
            txtCelular.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 6).toString());
            txtEmail.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 7).toString());
            TxtEndereco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 8).toString());
            txtCep.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 9).toString());
            txtCidade.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 10).toString());
            txtEstado.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 11).toString());
            txtTelefone.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 12).toString());
            txtSite.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 13).toString());
            txtBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 14).toString());
            txtAgencia.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 15).toString());
            txtConta.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 16).toString());
            txtNomeBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 17).toString());
            txtCpfBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 18).toString());
            txtPix.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 19).toString());
        }
    }//GEN-LAST:event_jTParceiro1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(jTParceiroFisico.getSelectedRow() != -1){
            DefaultTableModel modelo = (DefaultTableModel) jTParceiroFisico.getModel();
            modelo.removeRow(jTParceiroFisico.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um parceiro para excluir");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonAtualizar1ActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        readJTableForCpf(jPesquisar3.getText());
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRgActionPerformed

    private void jTParceiroFisicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTParceiroFisicoMouseClicked

        if(jTParceiroFisico.getSelectedRow() != -1){
            
            txtNome.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 1).toString());
            txtCpf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 2).toString());
            txtRg.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 3).toString());
            txtOrgaoEmissor.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 4).toString());
            txtUf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 5).toString());
            txtCelular.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 6).toString());
            txtEmail.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 7).toString());
            TxtEndereco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 8).toString());
            txtCep.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 9).toString());
            txtCidade.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 10).toString());
            txtEstado.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 11).toString());
            txtTelefone.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 12).toString());
            txtSite.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 13).toString());
            txtBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 14).toString());
            txtAgencia.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 15).toString());
            txtConta.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 16).toString());
            txtNomeBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 17).toString());
            txtCpfBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 18).toString());
            txtPix.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 19).toString());
        }
    }//GEN-LAST:event_jTParceiroFisicoMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

        if(jTParceiroFisico.getSelectedRow() != -1){
            ParceiroFisico p = new ParceiroFisico();
            ParceiroFisicoDAO dao = new ParceiroFisicoDAO();

            p.setId((int)jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 0));

            dao.delete(p);
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um parceiro para excluir");
        }
        readJTable();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizar2ActionPerformed

        ParceiroFisico p = new ParceiroFisico();
        ParceiroFisicoDAO dao = new ParceiroFisicoDAO();

        p.setNome(txtNome.getText());
        p.setCpf(txtCpf.getText());
        p.setRg(txtRg.getText());
        p.setOrgao_emissor(txtOrgaoEmissor.getText());
        p.setUf(txtUf.getText());
        p.setCelular(txtCelular.getText());
        p.setEmail(txtEmail.getText());
        p.setEndereco(TxtEndereco.getText());
        p.setCep(txtCep.getText());
        p.setCidade(txtCidade.getText());
        p.setEstado(txtEstado.getText());
        p.setTelefone(txtTelefone.getText());
        p.setSite(txtSite.getText());
        p.setBanco(txtBanco.getText());
        p.setAg(txtAgencia.getText());
        p.setCc(txtConta.getText());
        p.setNome_banco(txtNomeBanco.getText());
        p.setCpf_banco(txtCpfBanco.getText());
        p.setPix(txtPix.getText());
        p.setId((int) jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 0));
        dao.update(p);
        
        txtNome.setText("");
        txtCpf.setText("");
        txtRg.setText("");
        txtOrgaoEmissor.setText("");
        txtUf.setText("");
        txtCelular.setText("");
        txtEmail.setText("");
        TxtEndereco.setText("");
        txtCep.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtTelefone.setText("");
        txtSite.setText("");
        txtBanco.setText("");
        txtAgencia.setText("");
        txtConta.setText("");
        txtNomeBanco.setText("");
        txtCpfBanco.setText("");
        txtPix.setText("");

        
        readJTable();
    }//GEN-LAST:event_jButtonAtualizar2ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jTParceiroFisicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTParceiroFisicoKeyReleased

        if(jTParceiroFisico.getSelectedRow() != -1){
            
            txtNome.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 1).toString());
            txtCpf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 2).toString());
            txtRg.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 3).toString());
            txtOrgaoEmissor.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 4).toString());
            txtUf.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 5).toString());
            txtCelular.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 6).toString());
            txtEmail.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 7).toString());
            TxtEndereco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 8).toString());
            txtCep.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 9).toString());
            txtCidade.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 10).toString());
            txtEstado.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 11).toString());
            txtTelefone.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 12).toString());
            txtSite.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 13).toString());
            txtBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 14).toString());
            txtAgencia.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 15).toString());
            txtConta.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 16).toString());
            txtNomeBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 17).toString());
            txtCpfBanco.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 18).toString());
            txtPix.setText(jTParceiroFisico.getValueAt(jTParceiroFisico.getSelectedRow(), 19).toString());
        }

    }//GEN-LAST:event_jTParceiroFisicoKeyReleased

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed

        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(jTParceiroFisico.getPrintable(JTable.PrintMode.FIT_WIDTH, null, null));
        job.setJobName("Nome do Trabalho de impressão");
        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(PesquisaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtEndereco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonAtualizar1;
    private javax.swing.JButton jButtonAtualizar2;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jPesquisar;
    private javax.swing.JTextField jPesquisar1;
    private javax.swing.JTextField jPesquisar3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTParceiro;
    private javax.swing.JTable jTParceiro1;
    private javax.swing.JTable jTParceiroFisico;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCpfBanco;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEndereco1;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeBanco;
    private javax.swing.JTextField txtNomeFantasia;
    private javax.swing.JTextField txtNomeFantasia1;
    private javax.swing.JTextField txtOrgaoEmissor;
    private javax.swing.JTextField txtPix;
    private javax.swing.JTextField txtRazao;
    private javax.swing.JTextField txtRazao1;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtSite;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUf;
    // End of variables declaration//GEN-END:variables
}
