/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneCadastrarCliente = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenuCadastroCliente = new javax.swing.JMenuItem();
        jMenuPesquisarCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuParfisico = new javax.swing.JMenu();
        jMenuCadastroParceiroFisico = new javax.swing.JMenuItem();
        jMenuPesquisarParceiroFisico = new javax.swing.JMenuItem();
        jMenuParjuridico = new javax.swing.JMenu();
        jMenuCadParJuridico = new javax.swing.JMenuItem();
        jMenuIPesquisarParJuridico = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPaneCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPaneCadastrarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPaneCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setText("v1.2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1893, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(687, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(377, 377, 377))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        jMenu11.setForeground(new java.awt.Color(0, 0, 0));
        jMenu11.setText("Clientes");
        jMenu11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jMenuCadastroCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuCadastroCliente.setForeground(new java.awt.Color(0, 0, 0));
        jMenuCadastroCliente.setText("Cadastro");
        jMenuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroClienteActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuCadastroCliente);

        jMenuPesquisarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuPesquisarCliente.setForeground(new java.awt.Color(0, 0, 0));
        jMenuPesquisarCliente.setText("Pesquisar");
        jMenuPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisarClienteActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuPesquisarCliente);

        jMenuItem1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem1.setText("Documentos");
        jMenu11.add(jMenuItem1);

        jMenuBar3.add(jMenu11);

        jMenu12.setForeground(new java.awt.Color(0, 0, 0));
        jMenu12.setText("Parceiros");
        jMenu12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jMenuParfisico.setForeground(new java.awt.Color(0, 0, 0));
        jMenuParfisico.setText("Físico");
        jMenuParfisico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jMenuCadastroParceiroFisico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuCadastroParceiroFisico.setForeground(new java.awt.Color(0, 0, 0));
        jMenuCadastroParceiroFisico.setText("Cadastro");
        jMenuCadastroParceiroFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroParceiroFisicoActionPerformed(evt);
            }
        });
        jMenuParfisico.add(jMenuCadastroParceiroFisico);

        jMenuPesquisarParceiroFisico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuPesquisarParceiroFisico.setForeground(new java.awt.Color(0, 0, 0));
        jMenuPesquisarParceiroFisico.setText("Pesquisar");
        jMenuPesquisarParceiroFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisarParceiroFisicoActionPerformed(evt);
            }
        });
        jMenuParfisico.add(jMenuPesquisarParceiroFisico);

        jMenu12.add(jMenuParfisico);

        jMenuParjuridico.setForeground(new java.awt.Color(0, 0, 0));
        jMenuParjuridico.setText("Jurídico");
        jMenuParjuridico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jMenuCadParJuridico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuCadParJuridico.setForeground(new java.awt.Color(0, 0, 0));
        jMenuCadParJuridico.setText("Cadastro");
        jMenuCadParJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadParJuridicoActionPerformed(evt);
            }
        });
        jMenuParjuridico.add(jMenuCadParJuridico);

        jMenuIPesquisarParJuridico.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuIPesquisarParJuridico.setForeground(new java.awt.Color(0, 0, 0));
        jMenuIPesquisarParJuridico.setText("Pesquisar");
        jMenuIPesquisarParJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIPesquisarParJuridicoActionPerformed(evt);
            }
        });
        jMenuParjuridico.add(jMenuIPesquisarParJuridico);

        jMenu12.add(jMenuParjuridico);

        jMenuBar3.add(jMenu12);

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Financeiro");
        jMenu1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuBar3.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Relatórios");
        jMenu2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jMenuBar3.add(jMenu2);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroClienteActionPerformed
        
        CadastroCliente cadastroCliente = new CadastroCliente();
        jPanel1.add(cadastroCliente);
        cadastroCliente.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuCadastroClienteActionPerformed

    private void jMenuPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisarClienteActionPerformed

        PesquisaCliente pesquisaCliente = new PesquisaCliente();
        jPanel1.add(pesquisaCliente);
        pesquisaCliente.setVisible(true);

    }//GEN-LAST:event_jMenuPesquisarClienteActionPerformed

    private void jMenuCadastroParceiroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroParceiroFisicoActionPerformed

        CadastroParceiroFisico cadParFisico = new CadastroParceiroFisico();
        jPanel1.add(cadParFisico);
        cadParFisico.setVisible(true);

    }//GEN-LAST:event_jMenuCadastroParceiroFisicoActionPerformed

    private void jMenuPesquisarParceiroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisarParceiroFisicoActionPerformed

        PesquisarParceiroFisico pesqusarParFisico = new PesquisarParceiroFisico();
        jPanel1.add(pesqusarParFisico);
        pesqusarParFisico.setVisible(true);

    }//GEN-LAST:event_jMenuPesquisarParceiroFisicoActionPerformed

    private void jMenuCadParJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadParJuridicoActionPerformed
        
        CadastroParceiro cadPar = new CadastroParceiro();
        jPanel1.add(cadPar);
        cadPar.setVisible(true);

    }//GEN-LAST:event_jMenuCadParJuridicoActionPerformed

    private void jMenuIPesquisarParJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIPesquisarParJuridicoActionPerformed

        PesquisarParceiro PesquisarPar = new PesquisarParceiro();
        jPanel1.add(PesquisarPar);
        PesquisarPar.setVisible(true);

    }//GEN-LAST:event_jMenuIPesquisarParJuridicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneCadastrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuCadParJuridico;
    private javax.swing.JMenuItem jMenuCadastroCliente;
    private javax.swing.JMenuItem jMenuCadastroParceiroFisico;
    private javax.swing.JMenuItem jMenuIPesquisarParJuridico;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jMenuParfisico;
    private javax.swing.JMenu jMenuParjuridico;
    private javax.swing.JMenuItem jMenuPesquisarCliente;
    private javax.swing.JMenuItem jMenuPesquisarParceiroFisico;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
